In [1]:
import numpy as np

In [2]:
a = np.arange(15)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
a = a.reshape(3,5) #reshape the element of array

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.ndim  #no of axis in the array

2

In [7]:
a.shape #dimensions of array

(3, 5)

In [8]:
a.size #total number of elements of the array

15

In [9]:
a.dtype #type of the elements in the array

dtype('int32')

In [10]:
a.itemsize #the size in bytes of each element of the array

4

In [11]:
a.data #the buffer containing the actual elements of the array

In [12]:
c = np.array( [ [1,2], [3,4] ], dtype=complex ) #type of the array can also be explicitly specified at creation time

In [13]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [14]:
np.zeros((2, 4))  #function zeros creates an array full of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((2,3,4)) #function ones creates an array full of ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [16]:
np.empty((2,3)) #function empty creates an array whose initial content is random and depends on the state of the memory

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [18]:
np.linspace( 0, 2, 9 ) #total elements between the numbers

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )

In [20]:
A @ B  #dot product

array([[5, 4],
       [3, 4]])

In [21]:
A.dot(B) #also dot product

array([[5, 4],
       [3, 4]])

In [22]:
# rg = np.random.default_rng(1)
a = np.random.rand(3,5)

In [23]:
a

array([[0.28559913, 0.59404881, 0.27704917, 0.76174976, 0.8075828 ],
       [0.96879387, 0.10570406, 0.48450996, 0.235446  , 0.20515901],
       [0.06441391, 0.94556643, 0.9439129 , 0.26851078, 0.68836014]])

In [24]:
a.sum()

7.636406715357098

In [25]:
a.max()

0.9687938697584254

In [26]:
a.min()

0.06441391069447844

In [27]:
a.sum(axis=0)

array([1.31880691, 1.64531929, 1.70547202, 1.26570654, 1.70110196])

In [28]:
a.cumsum(axis = 0) #cumulative sum

array([[0.28559913, 0.59404881, 0.27704917, 0.76174976, 0.8075828 ],
       [1.254393  , 0.69975286, 0.76155912, 0.99719576, 1.01274181],
       [1.31880691, 1.64531929, 1.70547202, 1.26570654, 1.70110196]])

In [29]:
for i in a.flat: #access each element
    print(i)

0.2855991270687912
0.5940488054464946
0.2770491684031725
0.7617497580994708
0.8075828036722702
0.9687938697584254
0.10570405789732973
0.4845099550539441
0.2354459993415775
0.20515900746346116
0.06441391069447844
0.9455664289672208
0.9439128953075397
0.26851078426406927
0.6883601439188524
